/**
 * Caption post-processor.
 *
 * The caption draft is generated by Gemini in the scoring call.
 * This module validates and refines it before publishing:
 *
 *   1. Strips engagement-bait phrases
 *   2. Ensures #BriefSphere is present
 *   3. Ensures the source attribution line is present
 *   4. Enforces a character budget (Facebook: full text shown; truncation only in
 *      feed preview after ~300 chars — but we keep it readable end-to-end)
 *   5. Returns the cleaned, ready-to-post string
 */

const MAX_CAPTION_CHARS = 2_000;  // Facebook hard limit is 63,206 — we keep it short

/** Engagement bait phrases to detect and remove */
const BAIT_PATTERNS = [
  /comment\s+(yes|no)\s+if/gi,
  /tag\s+(a\s+)?(friend|someone|your)/gi,
  /share\s+if\s+you/gi,
  /like\s+if\s+you/gi,
  /double[\s-]tap\s+if/gi,
  /click\s+like\s+if/gi,
  /repost\s+if/gi,
  /follow\s+(us\s+)?for\s+more/gi,
];

/** Ensure #BriefSphere appears in the hashtag block */
function ensureBrandHashtag(text: string): string {
  if (text.includes('#BriefSphere') || text.includes('#briefsphere')) return text;

  // Find the hashtag block (lines starting with #) and prepend
  const lines = text.split('\n');
  const hashtagLineIdx = lines.findIndex((l) => l.trim().startsWith('#'));

  if (hashtagLineIdx !== -1) {
    lines[hashtagLineIdx] = '#BriefSphere ' + lines[hashtagLineIdx];
  } else {
    lines.push('#BriefSphere');
  }

  return lines.join('\n');
}

/** Remove detected engagement-bait phrases */
function stripEngagementBait(text: string): string {
  let clean = text;
  for (const pattern of BAIT_PATTERNS) {
    if (pattern.test(clean)) {
      console.warn('[caption] ⚠️  Engagement bait detected and removed');
      // Replace the offending sentence with a neutral placeholder
      clean = clean.replace(pattern, '[removed]');
    }
    pattern.lastIndex = 0;  // Reset regex state
  }
  return clean.replace(/\[removed\]/g, '').replace(/\s{2,}/g, ' ').trim();
}

/** Ensure the source attribution line is present */
function ensureSourceLine(text: string, sourceName: string): string {
  const sourcePattern = /📰\s*Source:/i;
  if (sourcePattern.test(text)) return text;

  // Not found — append it before the hashtag block
  const lines = text.split('\n');
  const hashtagLineIdx = lines.findIndex((l) => l.trim().startsWith('#'));

  const sourceLine = `📰 Source: ${sourceName}`;

  if (hashtagLineIdx !== -1) {
    lines.splice(hashtagLineIdx, 0, '', sourceLine);
  } else {
    lines.push('', sourceLine);
  }

  return lines.join('\n');
}

/** Trim to character budget, preserving hashtags at the end */
function applyCharBudget(text: string): string {
  if (text.length <= MAX_CAPTION_CHARS) return text;

  // Find the hashtag block
  const lines = text.split('\n');
  const hashtagLineIdx = lines.findIndex((l) => l.trim().startsWith('#'));

  if (hashtagLineIdx !== -1) {
    const hashtagSection = lines.slice(hashtagLineIdx).join('\n');
    const bodySection = lines.slice(0, hashtagLineIdx).join('\n');
    const budget = MAX_CAPTION_CHARS - hashtagSection.length - 4;  // 4 = '\n\n' + safety
    const trimmedBody = bodySection.slice(0, budget).trimEnd() + '…';
    return `${trimmedBody}\n\n${hashtagSection}`;
  }

  return text.slice(0, MAX_CAPTION_CHARS - 1) + '…';
}

/**
 * Process a raw caption draft into a final, publish-ready string.
 *
 * @param captionDraft  Raw output from Gemini (already structured)
 * @param sourceName    Source name for the attribution line (e.g. "Ada Derana")
 */
export function processCaption(captionDraft: string, sourceName: string): string {
  let caption = captionDraft.trim();

  // Pipeline
  caption = stripEngagementBait(caption);
  caption = ensureSourceLine(caption, sourceName);
  caption = ensureBrandHashtag(caption);
  caption = applyCharBudget(caption);

  return caption;
}
